name: totem_observer_client
description: Multiplayer Observer connection client.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC.ttf
